Migrate to Solidity5
omisego/plasma-mvp pull request #216
Opened 2019-02-21 13:10 UTC by ackintosh

Solidity5 has been released on 14 Nov 2018 and current version is [v0.5.4](https://github.com/ethereum/solidity/releases/tag/v0.5.4). 😎 

- [Release Version 0.5.0 · ethereum/solidity](https://github.com/ethereum/solidity/releases/tag/v0.5.0)
- [Solidity v0.5.0 Breaking Changes — Solidity 0.5.5 documentation](https://solidity.readthedocs.io/en/latest/050-breaking-changes.html)

2019-02-25 10:03 UTC, ackintosh commented
Currently, only the [`test_finalize_exits`](https://github.com/omisego/plasma-mvp/blob/48ea0983478a242db29195ac1c1f3be5cda9a107/tests/root_chain/contracts/root_chain/test_root_chain.py#L198) test  fails. 🙄💦 



<details>
<summary>Details</summary>


```sh
$ make test

python -m pytest
========================================================= test session starts ==========================================================
platform darwin -- Python 3.7.2, pytest-4.3.0, py-1.7.0, pluggy-0.8.1
rootdir: /Users/akihito1/src/github.com/ackintosh/plasma-mvp, inifile:
collected 37 items

tests/child_chain/test_block.py ..                                                                                               [  5%]
tests/child_chain/test_child_chain.py ........                                                                                   [ 27%]
tests/child_chain/test_child_chain_integration.py .....                                                                          [ 40%]
tests/child_chain/test_transaction.py .                                                                                          [ 43%]
tests/root_chain/contracts/data_structures/test_priority_queue.py .......                                                        [ 62%]
tests/root_chain/contracts/root_chain/test_root_chain.py .....F                                                                  [ 78%]
tests/utils/test_fixed_merkle.py ........                                                                                        [100%]

=============================================================== FAILURES ===============================================================
_________________________________________________________ test_finalize_exits __________________________________________________________

t = <module 'ethereum.tools.tester' from '/Users/akihito1/src/github.com/ackintosh/plasma-mvp/env/lib/python3.7/site-packages/ethereum-2.3.0-py3.7.egg/ethereum/tools/tester.py'>
u = <module 'ethereum.utils' from '/Users/akihito1/src/github.com/ackintosh/plasma-mvp/env/lib/python3.7/site-packages/ethereum-2.3.0-py3.7.egg/ethereum/utils.py'>
root_chain = <ethereum.tools.tester.ABIContract object at 0x10ba83d30>

    def test_finalize_exits(t, u, root_chain):
        two_weeks = 60 * 60 * 24 * 14
        owner, value_1, key = t.a1, 100, t.k1
        tx1 = Transaction(0, 0, 0, 0, 0, 0,
                          NULL_ADDRESS,
                          owner, value_1, NULL_ADDRESS, 0)
        dep1_blknum = root_chain.getDepositBlock()
        root_chain.deposit(value=value_1, sender=key)
        utxo_pos1 = encode_utxo_id(dep1_blknum, 0, 0)
        exit_bond = root_chain.EXIT_BOND()
        root_chain.startDepositExit(utxo_pos1, NULL_ADDRESS, tx1.amount1, sender=key, value=exit_bond)
        t.chain.head_state.timestamp += two_weeks * 2
        assert root_chain.exits(utxo_pos1) == ['0x' + owner.hex(), NULL_ADDRESS_HEX, 100]
        pre_balance = t.chain.head_state.get_balance(owner)
>       root_chain.finalizeExits(sender=t.k2)

tests/root_chain/contracts/root_chain/test_root_chain.py:212:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
env/lib/python3.7/site-packages/ethereum-2.3.0-py3.7.egg/ethereum/tools/tester.py:103: in kall
    gasprice=kwargs.get('gasprice', GASPRICE)
env/lib/python3.7/site-packages/ethereum-2.3.0-py3.7.egg/ethereum/tools/tester.py:194: in tx
    output = self.direct_tx(transaction)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ethereum.tools.tester.Chain object at 0x10dbb9978>, transaction = <Transaction(78e5)>

    def direct_tx(self, transaction):
        self.last_tx = transaction
        if self.last_sender is not None and privtoaddr(
                self.last_sender) != transaction.sender:
            self.last_sender = None
        success, output = apply_transaction(self.head_state, transaction)
        self.block.transactions.append(transaction)
        if not success:
>           raise TransactionFailed()
E           ethereum.tools.tester.TransactionFailed

env/lib/python3.7/site-packages/ethereum-2.3.0-py3.7.egg/ethereum/tools/tester.py:185: TransactionFailed
-------------------------------------------------------- Captured stdout setup ---------------------------------------------------------
Initializing chain from provided state
INFO:eth.block  Block pre-sealed, 4279013 gas used
INFO:eth.chain  Adding to head head=c6745cf3
Saved 4 address change logs
INFO:eth.chain  Added block 1 (5806fdd2) with 1 txs and 4279013 gas
=========================================================== warnings summary ===========================================================
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_no_sig
tests/child_chain/test_child_chain.py::test_send_tx_invalid_sig
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_submit_block
tests/child_chain/test_child_chain.py::test_submit_block_no_sig
tests/child_chain/test_child_chain.py::test_submit_block_invalid_sig
tests/child_chain/test_child_chain_integration.py::test_deposit
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_submit_block
tests/child_chain/test_child_chain_integration.py::test_withdraw_transfer
tests/child_chain/test_child_chain_integration.py::test_withdraw_deposit
  /Users/akihito1/src/github.com/ackintosh/plasma-mvp/plasma/root_chain/deployer.py:124: DeprecationWarning: deploy is deprecated in favor of contract.constructor.transact
    }, args=args)

tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_no_sig
tests/child_chain/test_child_chain.py::test_send_tx_invalid_sig
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_submit_block
tests/child_chain/test_child_chain_integration.py::test_deposit
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_submit_block
tests/child_chain/test_child_chain_integration.py::test_submit_block
tests/child_chain/test_child_chain_integration.py::test_withdraw_transfer
tests/child_chain/test_child_chain_integration.py::test_withdraw_transfer
tests/child_chain/test_child_chain_integration.py::test_withdraw_transfer
tests/child_chain/test_child_chain_integration.py::test_withdraw_deposit
tests/child_chain/test_child_chain_integration.py::test_withdraw_deposit
  /Users/akihito1/src/github.com/ackintosh/plasma-mvp/env/lib/python3.7/site-packages/web3-4.5.0-py3.7.egg/web3/utils/decorators.py:14: DeprecationWarning: transact is deprecated in favor of contract.<functions/events>.<method name>.transact
    return self.method(obj, *args, **kwargs)

tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests [...]

2019-02-27 11:47 UTC, ackintosh commented
Now all tests is passed. 💚The result shows 288 deprecation warnings, which may be addressed in  other PR.

<details>
<summary>Details</summary>

```sh
python -m pytest
========================================================= test session starts ==========================================================
platform darwin -- Python 3.7.2, pytest-4.3.0, py-1.7.0, pluggy-0.8.1
rootdir: /Users/akihito1/src/github.com/ackintosh/plasma-mvp, inifile:
collected 37 items

tests/child_chain/test_block.py ..                                                                                               [  5%]
tests/child_chain/test_child_chain.py ........                                                                                   [ 27%]
tests/child_chain/test_child_chain_integration.py .....                                                                          [ 40%]
tests/child_chain/test_transaction.py .                                                                                          [ 43%]
tests/root_chain/contracts/data_structures/test_priority_queue.py .......                                                        [ 62%]
tests/root_chain/contracts/root_chain/test_root_chain.py ......                                                                  [ 78%]
tests/utils/test_fixed_merkle.py ........                                                                                        [100%]

=========================================================== warnings summary ===========================================================
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_no_sig
tests/child_chain/test_child_chain.py::test_send_tx_invalid_sig
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_submit_block
tests/child_chain/test_child_chain.py::test_submit_block_no_sig
tests/child_chain/test_child_chain.py::test_submit_block_invalid_sig
tests/child_chain/test_child_chain_integration.py::test_deposit
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_submit_block
tests/child_chain/test_child_chain_integration.py::test_withdraw_transfer
tests/child_chain/test_child_chain_integration.py::test_withdraw_deposit
  /Users/akihito1/src/github.com/ackintosh/plasma-mvp/plasma/root_chain/deployer.py:124: DeprecationWarning: deploy is deprecated in favor of contract.constructor.transact
    }, args=args)

tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_no_sig
tests/child_chain/test_child_chain.py::test_send_tx_invalid_sig
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_submit_block
tests/child_chain/test_child_chain_integration.py::test_deposit
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_submit_block
tests/child_chain/test_child_chain_integration.py::test_submit_block
tests/child_chain/test_child_chain_integration.py::test_withdraw_transfer
tests/child_chain/test_child_chain_integration.py::test_withdraw_transfer
tests/child_chain/test_child_chain_integration.py::test_withdraw_transfer
tests/child_chain/test_child_chain_integration.py::test_withdraw_deposit
tests/child_chain/test_child_chain_integration.py::test_withdraw_deposit
  /Users/akihito1/src/github.com/ackintosh/plasma-mvp/env/lib/python3.7/site-packages/web3-4.5.0-py3.7.egg/web3/utils/decorators.py:14: DeprecationWarning: transact is deprecated in favor of contract.<functions/events>.<method name>.transact
    return self.method(obj, *args, **kwargs)

tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_apply_deposit
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_with_sig
tests/child_chain/test_child_chain.py::test_send_tx_no_sig
tests/child_chain/test_child_chain.py::test_send_tx_no_sig
tests/child_chain/test_child_chain.py::test_send_tx_no_sig
tests/child_chain/test_child_chain.py::test_send_tx_no_sig
tests/child_chain/test_child_chain.py::test_send_tx_no_sig
tests/child_chain/test_child_chain.py::test_send_tx_no_sig
tests/child_chain/test_child_chain.py::test_send_tx_invalid_sig
tests/child_chain/test_child_chain.py::test_send_tx_invalid_sig
tests/child_chain/test_child_chain.py::test_send_tx_invalid_sig
tests/child_chain/test_child_chain.py::test_send_tx_invalid_sig
tests/child_chain/test_child_chain.py::test_send_tx_invalid_sig
tests/child_chain/test_child_chain.py::test_send_tx_invalid_sig
tests/child_chain/test_child_chain.py::test_send_tx_invalid_sig
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_send_tx_double_spend
tests/child_chain/test_child_chain.py::test_submit_block
tests/child_chain/test_child_chain.py::test_submit_block
tests/child_chain/test_child_chain.py::test_submit_block
tests/child_chain/test_child_chain.py::test_submit_block
tests/child_chain/test_child_chain.py::test_submit_block
tests/child_chain/test_child_chain.py::test_submit_block
tests/child_chain/test_child_chain.py::test_submit_block_no_sig
tests/child_chain/test_child_chain.py::test_submit_block_invalid_sig
tests/child_chain/test_child_chain.py::test_submit_block_invalid_sig
tests/child_chain/test_child_chain_integration.py::test_deposit
tests/child_chain/test_child_chain_integration.py::test_deposit
tests/child_chain/test_child_chain_integration.py::test_deposit
tests/child_chain/test_child_chain_integration.py::test_deposit
tests/child_chain/test_child_chain_integration.py::test_deposit
tests/child_chain/test_child_chain_integration.py::test_deposit
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_chain/test_child_chain_integration.py::test_transfer
tests/child_ch [...]

2019-02-27 11:51 UTC, ackintosh commented
cc @kfichter

2019-03-04 10:30 UTC, ackintosh commented
@jbunce @kasima @pik694 @purbanow @robinclart @sirn @T-Dnzt 
Could anyone review this PR?

2019-03-04 12:11 UTC, pik694 requested changes
Just one minor clean-up needs to be done

2019-03-04 12:11 UTC, pik694 commented on plasma/root_chain/contracts/PlasmaRLP.sol
> +//    address payable exitor = RLPDecode.toAddress(txList[7 + 2 * oindex]);
I believe this is should be cleaned up

2019-03-04 12:31 UTC, ackintosh commented
Thanks for your review @pik694 . I've deleted that.

2019-03-04 13:04 UTC, pik694 approved these changes

2019-03-04 13:24 UTC, merged

2019-03-04 13:51 UTC, ackintosh commented
Ah, I just noticed the update...
https://github.com/omisego/plasma-mvp/commit/679958b084977f175da722a0a7990f2212a7c723
> This is an old research repo. No active work is being done here. Efforts in the direction of production-ready MVP plasma chain (MoreVP, ERC20, audits) are in https://github.com/omisego/plasma-contracts.